#!/usr/bin/env python3
"""Expose the conda packages an app asked for, one wrapper per command.

Every requested package is installed into one environment. Each command a
requested package provides (its files in bin/, according to conda-meta) is
started through a small wrapper, so the commands can go on PATH on their own:

  --mode path   every wrapper goes in /opt/software/bin, which the image puts at
                the end of PATH, so the system's own python3, perl and so on
                still come first
  --mode lmod   each package gets /opt/software/<name>/<version>/bin and an Lmod
                modulefile, /opt/modulefiles/<name>/<version>.lua, so that
                `module load samtools` adds samtools' commands and nothing else

A wrapper puts the environment's bin directory first on PATH, so a tool that
runs its own helper programs finds them, and sources the environment's
activation scripts, so variables conda packages set on activation (JAVA_HOME,
for one) are set. Then it execs the real program. Dependencies get no
wrappers: only what was asked for appears.

The build fails if a requested package is not in the environment, so the list
cannot drift away from what the image contains. /opt/software/packages.tsv
records what was set up: name, version, channel, commands and module.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from pathlib import Path

SOFTWARE = Path("/opt/software")
MODULEFILES = Path("/opt/modulefiles")

WRAPPER = """#!/usr/bin/env bash
# {command} from the conda package {name} {version}; generated by make-conda-wrappers.py
export CONDA_PREFIX="{prefix}"
export PATH="{prefix}/bin:${{PATH}}"
for _activate in "{prefix}"/etc/conda/activate.d/*.sh; do
    [ -r "${{_activate}}" ] && . "${{_activate}}"
done
unset _activate
exec "{prefix}/bin/{command}" "$@"
"""

MODULEFILE = """-- {name} {version}, from conda; generated by make-conda-wrappers.py
help([[
{name} {version}, installed from the conda channel {channel}.

Commands: {commands}
]])

whatis("Name: {name}")
whatis("Version: {version}")
whatis("Commands: {commands}")

prepend_path("PATH", "{bindir}")
"""


def read_records(prefix: Path) -> dict[str, dict]:
    """Installed packages, by lower-case name, from the environment's conda-meta."""
    records = {}
    for meta in sorted((prefix / "conda-meta").glob("*.json")):
        try:
            data = json.loads(meta.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        if data.get("name"):
            records[data["name"].lower()] = data
    return records


def files_of(record: dict) -> list[str]:
    files = record.get("files")
    if files:
        return list(files)
    paths = (record.get("paths_data") or {}).get("paths", [])
    return [p.get("_path") or p.get("path") for p in paths if p.get("_path") or p.get("path")]


def commands_of(record: dict, prefix: Path) -> list[str]:
    commands = set()
    for path in files_of(record):
        if not path.startswith("bin/"):
            continue
        command = path[len("bin/"):]
        if not command or "/" in command or command.startswith("."):
            continue
        target = prefix / "bin" / command
        if target.is_file() and os.access(target, os.X_OK):
            commands.add(command)
    return sorted(commands)


def channel_of(record: dict) -> str:
    """'https://conda.anaconda.org/bioconda/linux-64' -> 'bioconda'."""
    parts = [p for p in str(record.get("channel") or "").rstrip("/").split("/") if p]
    if parts and parts[-1] in ("linux-64", "noarch"):
        parts.pop()
    return parts[-1] if parts else "unknown"


def write_wrapper(bindir: Path, command: str, name: str, version: str, prefix: Path) -> None:
    path = bindir / command
    path.write_text(
        WRAPPER.format(command=command, name=name, version=version, prefix=prefix),
        encoding="utf-8",
    )
    path.chmod(0o755)


def system_path() -> str:
    """PATH without the wrappers, to spot commands the system already provides."""
    return os.pathsep.join(
        p for p in os.environ.get("PATH", "").split(os.pathsep) if not p.startswith(str(SOFTWARE))
    )


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--prefix", required=True, type=Path, help="the conda environment")
    ap.add_argument("--packages", required=True, type=Path, help="requested package names, one per line")
    ap.add_argument("--mode", required=True, choices=["path", "lmod"])
    args = ap.parse_args(argv)

    wanted = []
    for line in args.packages.read_text(encoding="utf-8").splitlines():
        line = line.strip().lower()
        if line and not line.startswith("#"):
            wanted.append(line)

    records = read_records(args.prefix)
    missing = [name for name in wanted if name not in records]
    if missing:
        print(
            "make-conda-wrappers: ERROR: requested but not installed in "
            f"{args.prefix}: {', '.join(missing)}",
            file=sys.stderr,
        )
        return 1

    SOFTWARE.mkdir(parents=True, exist_ok=True)
    rows = []
    owner: dict[str, str] = {}
    for name in wanted:
        record = records[name]
        version = str(record.get("version", "unknown"))
        channel = channel_of(record)
        commands = commands_of(record, args.prefix)
        if not commands:
            print(f"make-conda-wrappers: {name} {version} has no commands; it is installed, nothing goes on PATH")
            rows.append([name, version, channel, "", ""])
            continue

        if args.mode == "path":
            bindir = SOFTWARE / "bin"
        else:
            bindir = SOFTWARE / name / version / "bin"
        bindir.mkdir(parents=True, exist_ok=True)

        written = []
        for command in commands:
            if args.mode == "path" and command in owner:
                print(
                    f"make-conda-wrappers: {command} comes with both {owner[command]} and {name}; "
                    f"keeping the one from {owner[command]}"
                )
                continue
            owner[command] = name
            write_wrapper(bindir, command, name, version, args.prefix)
            written.append(command)
            if args.mode == "path" and shutil.which(command, path=system_path()):
                print(
                    f"make-conda-wrappers: note: {command} is also a system command, which comes "
                    f"first on PATH; {name}'s is {bindir / command}"
                )

        module = ""
        if args.mode == "lmod":
            moddir = MODULEFILES / name
            moddir.mkdir(parents=True, exist_ok=True)
            (moddir / f"{version}.lua").write_text(
                MODULEFILE.format(
                    name=name,
                    version=version,
                    channel=channel,
                    commands=" ".join(written),
                    bindir=bindir,
                ),
                encoding="utf-8",
            )
            module = f"{name}/{version}"
        rows.append([name, version, channel, " ".join(written), module])

    with open(SOFTWARE / "packages.tsv", "w", encoding="utf-8") as fh:
        fh.write("name\tversion\tchannel\tcommands\tmodule\n")
        for row in rows:
            fh.write("\t".join(row) + "\n")

    width = max(len(r[0]) for r in rows)
    for name, version, channel, commands, module in rows:
        where = f"module load {module}" if module else ("on PATH" if commands else "no commands")
        print(f"make-conda-wrappers: {name:<{width}} {version:<12} {channel:<12} {where}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
