{% include "partials/header.Dockerfile.j2" %}

FROM ubuntu:{{ pins.ubuntu }}

{% include "partials/system-ubuntu.Dockerfile.j2" %}

{% include "partials/ood-k8s.Dockerfile.j2" %}
{% include "partials/apt.Dockerfile.j2" %}
{% include "partials/lmod.Dockerfile.j2" %}
{% include "partials/gpu.Dockerfile.j2" %}
{% include "partials/slurm.Dockerfile.j2" %}
{% include "partials/nesi-tools.Dockerfile.j2" %}
{% include "partials/conda.Dockerfile.j2" %}

# install JupyterLab
RUN {{ pip }} install jupyterlab
{% if pip_packages %}

# Python packages requested in the app spec (docker/requirements.txt)
COPY requirements.txt /opt/app-creator/requirements.txt
RUN {{ pip }} install -r /opt/app-creator/requirements.txt
{% endif %}
{% include "partials/data.Dockerfile.j2" %}
{% include "partials/custom.Dockerfile.j2" %}
{% include "partials/smoke-test.Dockerfile.j2" %}
